### PR TITLE
--registry sets all containers

### LINKED ISSUE #89: In Black Duck native mode, use registry set value for Postgres and Binary scanner images
**What happened**:
In Black Duck native mode, use registry set value for Postgres and Binary scanner images

**What you expected to happen**:
In Black Duck native mode, registry provided value should have been set in Postgres and Binary scanner images in their corresponding deployment

**How to reproduce it (as minimally and precisely as possible)**:
Set the registry flag to docker.io/xxxx and see Postgres and binary scanner images in their corresponding deployment

### PR DESCRIPTION
**Pull request by mphammer**
fixes #89

### CODE REVIEW

File: pkg/blackduck/ctl_blackduck.go [hunk 1]
```diff
@@ -235,171 +227,254 @@ func FlagWasSet(flagset *pflag.FlagSet, flagName string) bool {
...
-				if len(values) != 2 {
-					panic(fmt.Errorf("invalid environ configuration for %s", value))
+// GenerateHelmFlagsFromCobraFlags checks each flag in synopsysctl and updates the map to
+// contain the corresponding helm chart field and value
+func (ctl *HelmValuesFromCobraFlags) GenerateHelmFlagsFromCobraFlags(flagset *pflag.FlagSet) (map[string]interface{}, error) {
+	err := ctl.CheckValuesFromFlags(flagset)
+	if err != nil {
+		return nil, err
+	}
+	flagset.VisitAll(func(f *pflag.Flag) {
```
Comment (msenmurugan) [inline pkg/blackduck/ctl_blackduck.go:257]: The purpose ignoring the method to add the function directly is to report all errors at once instead of them reporting individually. Currently we are logging fatal exception which might not solve that use case.

Comment (mphammer) [reply pkg/blackduck/ctl_blackduck.go:257]: I made it like this so that the cases would have access to the flagset instead of just individual flags... but I switched all the Fatalf() instances to Errorf()  :)

**Review by msenmurugan — APPROVED** [review]
/lgtm
