### PR TITLE
Fix custom size blackduck

### LINKED ISSUE #70: Bug - Deployment resource flag values are not updating during Black Duck update
**What happened**:
During Black Duck update, if customer provides deployment resource file to override certain size of the container, it is not updating properly

**What you expected to happen**:
All the custom values of CPU, memory request and limit, replicas of a container need to be updated in the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Create a small sized Black Duck using synopsysctl and then try to increase the replicas of Black Duck scan container to 2. An update process is completing successfully but the values are not updating in the container

### PR DESCRIPTION
**Pull request by msenmurugan**
fixes #70

### CODE REVIEW

File: pkg/util/helm_helpers.go [hunk 1]
```diff
@@ -299,6 +259,30 @@ func GetWithHelm3(releaseName, namespace, kubeConfig string) (*release.Release,
 	return nil, fmt.Errorf("unable to find release '%s' in namespace '%s'", releaseName, namespace)
 }
 
+// GetBlackDuckChartAndReleaseWithHelm3 checks whether an file exist in the chart. If exist, it will convert the file to map and return the map
+func GetBlackDuckChartAndReleaseWithHelm3(namespace, kubeConfig, chartURL, fileName string) (map[string]interface{}, error) {
```
Comment (mphammer) [inline pkg/util/helm_helpers.go]: Can we rename this function to something more clear - like GetValuesFromFileInHelmChart() ?
* It isn't specific to Black Duck
* The name doesn't say that it's doing anything with Values

File: pkg/util/helm_helpers.go [hunk 2]
```diff
@@ -299,6 +259,30 @@ func GetWithHelm3(releaseName, namespace, kubeConfig string) (*release.Release,
...
+	if err != nil {
+		return nil, fmt.Errorf("failed to load release at '%s' for getting size: %s", chartURL, err)
+	}
+	validInstallableChart, err := isChartInstallable(chart)
+	if !validInstallableChart {
+		return nil, err
+	}
+
+	fileValues := map[string]interface{}{}
+	if err := mergeExtraFilesToConfig(chart, fileValues, []string{fileName}); err != nil {
```
Comment (mphammer) [inline pkg/util/helm_helpers.go]: Can we rename this function to something more clear - like mergeWithExtraFilesFromChart() ?
* It isn't doing anything with the config

**Review by mphammer — APPROVED** [review]
